Title:			Basic Presentation Skills  
				Grade 12    
Author:			Dylan Fitzgerald  
Affiliation: 	Fatima Senior Secondary School of Bwiam, The Gambia  
             	Peace Corps/The Gambia  
Email:			dylan@dylanfitzgerald.net  
Date:			October 25, 2010  
Format: 		Complete
Keywords: 		plan, curriculum, ICT, gambia, powerpoint, fatima
Language: 		English


# Basic Presentation Skills #

## Abstract ##

As a precursor to talking about Microsoft PowerPoint—that being software used to support presentations—we first have to talk about presentations in a formal setting.

## Goals ##

On completion of this lesson, students will:

 * Be exposed to a structured presentation format with support material
 * Demonstrate proficiency at planning the structure of a presentation
 * Demonstrate proficiency at presenting a planned, structured presentation

## Materials ##

 * Blackboard
 * Chalk

## Introduction ##

You've now had a chance to spend time playing with Microsoft PowerPoint, and to become familiar with its interface—the buttons and menus, the clip art, the transitions.  But what's it all for?  PowerPoint, like Word and Excel, is a software program, a tool, with a specific purpose.  Do you know what that purpose is?  

Drive conversation toward: PowerPoint is a tool for creating structured presentations.  

Discuss presentations: who's had to present at the board before? Given an oral report? Showed another student how to do something? Formal vs. informal, etc.

Who usually gives presentations, where, and why?

Informal, unstructured presentations can be anything! You explaining to your classmates how to do a maths problem is a form of informal presentation.

Structured presentations are planned in advance, so they have an agenda, or schedule, or list of things to cover, and shouldn't jump into other topics.  They also have a beginning, a middle, and an end.

Today, we're going to explore structured presentations, because that's what PowerPoint is designed to support.

## Lecture ##
## Practice ##
## Assessment ##
## Closure ##