Title:			Basic Presentation Skills  
				Grade 12    
Author:			Dylan Fitzgerald  
Affiliation: Fatima Senior Secondary School of Bwiam, The Gambia  
             Peace Corps/The Gambia  
Email:			dylan@dylanfitzgerald.net  
Date:			October 24, 2010  
Format: 		Complete
Keywords: 		plan, curriculum, ICT, gambia, powerpoint, fatima
Language: 		English


# Basic Presentation Skills #

## Introduction ##

As a precursor to talking about Microsoft PowerPoint—that being software used to support presentations—we first have to talk about presentations in a formal setting.

## Goals ##

On completion of this lesson, students will:

 * Be exposed to a structured presentation format with support material
 * 

## Materials ##

 * Blackboard
 * Chalk

Introduction
Lecture
Practice
Assessment
Closure